const event = {
  type: 'REQUEST',
  methodArn: 'arn:aws:execute-api:eu-west-1:607922367699:on0m1rx2yh/dev/POST/tokenservice/tokenize',
  resource: '/tokenservice/tokenize',
  path: '/tokenservice/tokenize',
  httpMethod: 'POST',
  headers: {
    Accept: '*/*',
    'CloudFront-Viewer-Country': 'ES',
    'CloudFront-Forwarded-Proto': 'https',
    'CloudFront-Is-Tablet-Viewer': 'false',
    'CloudFront-Is-Mobile-Viewer': 'false',
    'User-Agent': 'PostmanRuntime/7.1.1',
    'X-Forwarded-Proto': 'https',
    'CloudFront-Is-SmartTV-Viewer': 'false',
    Host: 'on0m1rx2yh.execute-api.eu-west-1.amazonaws.com',
    'Accept-Encoding': 'gzip, deflate',
    'X-Forwarded-Port': '443',
    'X-Amzn-Trace-Id': 'Root=1-5aae5696-d73b8151f251a044270cbb0a',
    Via: '1.1 f4aa73a94067eadbec8e3dbb21c8d196.cloudfront.net (CloudFront)',
    Authorization: 'Bearer 222222',
    'X-Amz-Cf-Id': 'BfML-eTBR-Tjbd5_AIoeNiTfLZOWD0eZCqzt2Ed2_XO_m1Np4XgnjA==',
    'X-Forwarded-For': '81.184.204.95, 52.46.44.91',
    'Postman-Token': '89d6ebf3-896f-4da5-86d3-98aa0b131f06',
    'cache-control': 'no-cache',
    'Content-Length': '36',
    'CloudFront-Is-Desktop-Viewer': 'true',
    'Content-Type': 'application/json',
  },
  queryStringParameters: {},
  pathParameters: {},
  stageVariables: {},
  requestContext: {
    requestTime: '18/Mar/2018:12:07:50 +0000',
    path: '/dev/tokenservice/tokenize',
    accountId: '607922367699',
    protocol: 'HTTP/1.1',
    resourceId: 't3q4ln',
    stage: 'dev',
    requestTimeEpoch: 1521374870938,
    requestId: 'fb07902d-2aa4-11e8-b643-472f871f8952',
    identity: {
      cognitoIdentityPoolId: null,
      accountId: null,
      cognitoIdentityId: null,
      caller: null,
      sourceIp: '81.184.204.95',
      accessKey: null,
      cognitoAuthenticationType: null,
      cognitoAuthenticationProvider: null,
      userArn: null,
      userAgent: 'PostmanRuntime/7.1.1',
      user: null,
    },
    resourcePath: '/tokenservice/tokenize',
    httpMethod: 'POST',
    apiId: 'on0m1rx2yh',
  },
};
